# Generated by Django 3.0.7 on 2020-06-15 15:48

from django.db import migrations


def create_data(apps, schema_editor):
    BusStops = apps.get_model('bus_stops', 'BusStops')
    BusStops(name="CityCenterTest", stopID=1, longitude=-6.260316, latitude=53.349309).save()


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
