# Generated by Django 3.0.7 on 2020-06-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_auto_20200616_1602'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busstops',
            table='bus_stops',
        ),
    ]
