# Generated by Django 3.0.7 on 2020-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routesstops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=10, null=True)),
                ('stopid', models.CharField(blank=True, max_length=10, null=True)),
                ('progr_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routesstops',
                'managed': False,
            },
        ),
    ]
